# https://github.com/cncf/foundation/blob/main/policies-guidance/allowed-third-party-license-policy.md
allow-licenses:
# default allowed
- 'Apache-2.0'
# explicit CNCF allowlist
- '0BSD'
- 'BSD-2-Clause'
- 'BSD-2-Clause-FreeBSD'
- 'BSD-3-Clause'
- 'ISC'
- 'MIT'
- 'MIT-0'
- 'OpenSSL'
- 'OpenSSL-standalone'
- 'PSF-2.0'
- 'PostgreSQL'
- 'Python-2.0'
- 'Python-2.0.1'
- 'SSLeay-standalone'
- 'UPL-1.0'
- 'X11'
- 'Zlib'
# Google's patent licence for Go
- 'LicenseRef-scancode-google-patent-license-golang'
# lightningcss pulled in by @tailwindcss
- 'MPL-2.0'

allow-dependencies-licenses:
# CC-BY-4.0: Build dependency pulled in by Next & browserslist
- 'pkg:npm/caniuse-lite'
# LGPL/MPL: Image optimization for Next
- 'pkg:npm/%40img/sharp-libvips-darwin-arm64'
- 'pkg:npm/%40img/sharp-libvips-darwin-x64'
- 'pkg:npm/%40img/sharp-libvips-linux-arm'
- 'pkg:npm/%40img/sharp-libvips-linux-arm64'
- 'pkg:npm/%40img/sharp-libvips-linux-ppc64'
- 'pkg:npm/%40img/sharp-libvips-linux-riscv64'
- 'pkg:npm/%40img/sharp-libvips-linux-s390x'
- 'pkg:npm/%40img/sharp-libvips-linux-x64'
- 'pkg:npm/%40img/sharp-libvips-linuxmusl-arm64'
- 'pkg:npm/%40img/sharp-libvips-linuxmusl-x64'
- 'pkg:npm/%40img/sharp-win32-arm64'
- 'pkg:npm/%40img/sharp-win32-ia32'
- 'pkg:npm/%40img/sharp-win32-x64'
# CC0-1.0: Pulled in by storybook
- 'pkg:npm/type-fest'
# Missing license: Build dependency
- 'pkg:npm/baseline-browser-mapping'