import React from 'react';

import type { Meta, StoryObj } from '@storybook/react';

import { ProjectDetailsData } from '@/app/(routegroups)/(projectroutes)/projects/[projectSlug]/project-details/page';

import ProjectDetailsPage from './projectDetailsPage';

const mockProject: ProjectDetailsData['project'] = {
  id: 1,
  name: 'test-project',
  gitUrl: 'git@github.com:example/test-project.git',
  created: '2024-01-15T10:30:00Z',
  branches: 'main,develop,feature/*',
  pullrequests: true,
  productionEnvironment: 'main',
  standbyProductionEnvironment: null,
  productionRoutes: 'https://example.com',
  standbyRoutes: null,
  developmentEnvironmentsLimit: 5,
  environments: [
    { environmentType: 'production' },
    { environmentType: 'development' },
    { environmentType: 'development' },
  ],
  autogeneratedRouteConfig: {
    updated: '2024-06-01T00:00:00Z',
    enabled: true,
    allowPullRequests: true,
    prefixes: ['www', 'api'],
    tlsAcme: true,
    insecure: 'Redirect',
    pathRoutes: [],
    disableRequestVerification: false,
  },
};

const meta: Meta<typeof ProjectDetailsPage> = {
  title: 'Pages/Project/Details',
  component: ProjectDetailsPage,
  parameters: {
    layout: 'fullscreen',
    nextjs: {
      appDirectory: true,
    },
  },
};

export default meta;
type Story = StoryObj<typeof ProjectDetailsPage>;

export const Default: Story = {
  args: {
    project: mockProject,
  },
};

export const WithoutAutogeneratedRoutes: Story = {
  args: {
    project: {
      ...mockProject,
      autogeneratedRouteConfig: undefined,
    },
  },
};

export const MinimalConfig: Story = {
  args: {
    project: {
      ...mockProject,
      branches: 'main',
      pullrequests: false,
      environments: [{ environmentType: 'production' }],
      autogeneratedRouteConfig: {
        updated: '2024-06-01T00:00:00Z',
        enabled: false,
        allowPullRequests: false,
        prefixes: [],
        tlsAcme: false,
        insecure: 'Allow',
        pathRoutes: [],
        disableRequestVerification: false,

      },
    },
  },
};
