/// <reference types="node" />
import * as fs from 'fs';
import * as path from 'path';

const EXTENSIONS_DIR = 'extensions';
const OUTPUT_MANIFEST = 'extensions.json';
const APP_DIR = 'src/app/(routegroups)';
const NEXT_TYPES_DIR = '.next/types';
const COMPONENTS_DIR = 'src/components/extensions';
const LIB_DIR = 'src/lib/extensions';
const REGISTRY_FILE = 'src/components/extensions/registry.ts';

// essentially inverse of the logic in build-extensions.ts - finds and removes all extension files
function findExtensions(): string[] {
  if (!fs.existsSync(EXTENSIONS_DIR)) {
    console.log(`No ${EXTENSIONS_DIR}/ directory found`);
    return [];
  }
  return fs.readdirSync(EXTENSIONS_DIR).filter((name: string) => {
    const extPath = path.join(EXTENSIONS_DIR, name);
    const manifestPath = path.join(extPath, 'extension.json');
    return fs.statSync(extPath).isDirectory() && fs.existsSync(manifestPath);
  });
}

function findDirs(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const entries = fs.readdirSync(dir);
  const hasFiles = entries.some((e: string) => fs.statSync(path.join(dir, e)).isFile());
  if (hasFiles) return [dir];
  return entries.flatMap((e: string) => findDirs(path.join(dir, e)));
}

function pruneEmptyDirs(dir: string, stopAt: string): void {
  if (dir === stopAt || !fs.existsSync(dir)) return;
  if (fs.readdirSync(dir).length === 0) {
    fs.rmdirSync(dir);
    pruneEmptyDirs(path.dirname(dir), stopAt);
  }
}

function removePages(extName: string): void {
  const pagesDir = path.join(EXTENSIONS_DIR, extName, 'pages');
  if (!fs.existsSync(pagesDir)) return;
  const dirs = findDirs(pagesDir);
  if (!dirs.length) return;
  console.log(`  Removing pages...`);
  for (const srcDir of dirs) {
    const rel = path.relative(pagesDir, srcDir);
    const destDir = path.join(APP_DIR, rel);
    if (fs.existsSync(destDir)) {
      fs.rmSync(destDir, { recursive: true, force: true });
      console.log(`    ${destDir}`);
      pruneEmptyDirs(path.dirname(destDir), APP_DIR);
    }
  }
}

function clearNextTypes(): void {
  if (!fs.existsSync(NEXT_TYPES_DIR)) return;
  fs.rmSync(NEXT_TYPES_DIR, { recursive: true, force: true });
  console.log(`  Cleared ${NEXT_TYPES_DIR}`);
}

function removeComponents(extName: string): void {
  const destDir = path.join(COMPONENTS_DIR, extName);
  if (!fs.existsSync(destDir)) return;
  console.log(`  Removing components...`);
  fs.rmSync(destDir, { recursive: true, force: true });
  console.log(`    ${destDir}`);
}

function removeLib(extName: string): void {
  const destDir = path.join(LIB_DIR, extName);
  if (!fs.existsSync(destDir)) return;
  console.log(`  Removing lib...`);
  fs.rmSync(destDir, { recursive: true, force: true });
  console.log(`    ${destDir}`);
}

function generateRegistry(): void {
  fs.writeFileSync(
    REGISTRY_FILE,
    [
      '// AUTO-GENERATED by scripts/build-extensions.ts',
      '',
      'type LazyFactory = () => Promise<any>;',
      '',
      'export const extensionComponentRegistry: Record<string, LazyFactory> = {};',
      '',
    ].join('\n')
  );
  console.log(`  Wrote registry: ${REGISTRY_FILE}`);
}

function main(): void {
  console.log('Removing all extensions...\n');
  const extensions = findExtensions();
  console.log(`Found ${extensions.length} extension(s): ${extensions.join(', ') || '(none)'}\n`);

  for (const extName of extensions) {
    console.log(`Processing: ${extName}`);
    removePages(extName);
    removeComponents(extName);
    removeLib(extName);
    console.log(`  ✓ ${extName}\n`);
  }

  generateRegistry();

  fs.writeFileSync(OUTPUT_MANIFEST, JSON.stringify({ extensions: [] }, null, 2));
  console.log(`\nWrote ${OUTPUT_MANIFEST} with 0 extension(s)`);
  clearNextTypes();
}

main();
