/// <reference types="node" />
import * as fs from 'fs';
import * as path from 'path';

const EXTENSIONS_DIR = 'extensions';
const OUTPUT_MANIFEST = 'extensions.json';
const APP_DIR = 'src/app/(routegroups)';
const NEXT_TYPES_DIR = '.next/types';
const COMPONENTS_DIR = 'src/components/extensions';
const LIB_DIR = 'src/lib/extensions';
const REGISTRY_FILE = 'src/components/extensions/registry.ts';

// essentially inverse of the logic in build-extensions.ts - finds and removes the extension files for a given extension
function findDirs(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const entries = fs.readdirSync(dir);
  const hasFiles = entries.some((e: string) => fs.statSync(path.join(dir, e)).isFile());
  if (hasFiles) return [dir];
  return entries.flatMap((e: string) => findDirs(path.join(dir, e)));
}

function pruneEmptyDirs(dir: string, stopAt: string): void {
  if (dir === stopAt || !fs.existsSync(dir)) return;
  if (fs.readdirSync(dir).length === 0) {
    fs.rmdirSync(dir);
    pruneEmptyDirs(path.dirname(dir), stopAt);
  }
}

function removePages(extName: string): void {
  const pagesDir = path.join(EXTENSIONS_DIR, extName, 'pages');
  if (!fs.existsSync(pagesDir)) return;
  const dirs = findDirs(pagesDir);
  if (!dirs.length) return;
  console.log(`  Removing pages...`);
  for (const srcDir of dirs) {
    const rel = path.relative(pagesDir, srcDir);
    const destDir = path.join(APP_DIR, rel);
    if (fs.existsSync(destDir)) {
      fs.rmSync(destDir, { recursive: true, force: true });
      console.log(`    ${destDir}`);
      pruneEmptyDirs(path.dirname(destDir), APP_DIR);
    }
  }
}

function clearNextTypes(): void {
  if (!fs.existsSync(NEXT_TYPES_DIR)) return;
  fs.rmSync(NEXT_TYPES_DIR, { recursive: true, force: true });
  console.log(`  Cleared ${NEXT_TYPES_DIR}`);
}

function removeComponents(extName: string): void {
  const destDir = path.join(COMPONENTS_DIR, extName);
  if (!fs.existsSync(destDir)) return;
  console.log(`  Removing components...`);
  fs.rmSync(destDir, { recursive: true, force: true });
  console.log(`    ${destDir}`);
}

function removeLib(extName: string): void {
  const destDir = path.join(LIB_DIR, extName);
  if (!fs.existsSync(destDir)) return;
  console.log(`  Removing lib...`);
  fs.rmSync(destDir, { recursive: true, force: true });
  console.log(`    ${destDir}`);
}

function collectComponentNames(extName: string): string[] {
  const destDir = path.join(COMPONENTS_DIR, extName);
  if (!fs.existsSync(destDir)) return [];
  return fs.readdirSync(destDir)
    .filter((f: string) => /\.(tsx|ts)$/.test(f) && f !== 'index.ts' && f !== 'index.tsx')
    .map((f: string) => f.replace(/\.(tsx|ts)$/, ''));
}

function remainingExtensionComponents(): string[] {
  if (!fs.existsSync(COMPONENTS_DIR)) return [];
  return fs.readdirSync(COMPONENTS_DIR).filter((entry: string) =>
    fs.statSync(path.join(COMPONENTS_DIR, entry)).isDirectory()
  );
}

function generateRegistry(extensions: string[]): void {
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/build-extensions.ts',
    '',
    'type LazyFactory = () => Promise<any>;',
    '',
    'export const extensionComponentRegistry: Record<string, LazyFactory> = {',
  ];

  for (const extName of extensions) {
    const componentNames = collectComponentNames(extName);
    for (const name of componentNames) {
      lines.push(`  '${extName}/${name}': () => import('./${extName}/${name}'),`);
    }
  }

  lines.push('};', '');

  fs.writeFileSync(REGISTRY_FILE, lines.join('\n'));
  console.log(`  Wrote registry: ${REGISTRY_FILE}`);
}

function removeFromManifest(extName: string): void {
  if (!fs.existsSync(OUTPUT_MANIFEST)) return;
  const manifest = JSON.parse(fs.readFileSync(OUTPUT_MANIFEST, 'utf-8')) as {
    extensions: { meta: { name: string } }[];
  };
  manifest.extensions = manifest.extensions.filter((e: { meta: { name: string } }) => e.meta.name !== extName);
  fs.writeFileSync(OUTPUT_MANIFEST, JSON.stringify(manifest, null, 2));
  console.log(`  Updated ${OUTPUT_MANIFEST}`);
}

function main(): void {
  const extName = process.argv[2];
  if (!extName) {
    process.exit(1);
  }

  const manifestPath = path.join(EXTENSIONS_DIR, extName, 'extension.json');
  if (!fs.existsSync(manifestPath)) {
    console.error(`No extension.json found for "${extName}" at ${manifestPath}`);
    process.exit(1);
  }

  console.log(`Removing extension: ${extName}\n`);

  removePages(extName);
  removeComponents(extName);
  removeLib(extName);
  generateRegistry(remainingExtensionComponents());
  removeFromManifest(extName);
  clearNextTypes();

  console.log(`\n✓ ${extName} removed`);
}

main();
